name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
env:
  REPO: ghcr.io/${{ github.repository_owner }}
jobs:
  ci:
    if: github.event.pull_request.draft == false
    name: Test and build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - name: Unit tests
        run: make test
      - name: Build image
        run: make build-image
